const { wrapper, formatDate, formatDateTime } = require('./pdfLayout');

// cert: a single MedicalCertificate row, already joined with patient_first_name/
// patient_last_name and dentist_first_name/dentist_last_name (see
// medicalCertificateModel.createCertificate / findCertificateById).
const medicalCertificateHtml = (cert, clinicName, logoUrl) => {
  const dayCount =
    Math.round((new Date(cert.rest_to) - new Date(cert.rest_from)) / (1000 * 60 * 60 * 24)) + 1;

  const bodyHtml = `
    <div class="meta-row"><span class="label">Patient</span><b>${cert.patient_first_name} ${cert.patient_last_name}</b></div>
    <div class="meta-row"><span class="label">Date of visit</span><b>${formatDate(cert.visit_date)}</b></div>

    <div class="section-title">Reason for visit / diagnosis</div>
    <p style="font-size:12.5px; line-height:1.6; margin:4px 0 0;">${cert.diagnosis_summary}</p>

    <div class="section-title">Recommended rest period</div>
    <div class="meta-row"><span class="label">From</span><b>${formatDate(cert.rest_from)}</b></div>
    <div class="meta-row"><span class="label">To</span><b>${formatDate(cert.rest_to)}</b></div>
    <div class="meta-row"><span class="label">Total days</span><b>${dayCount} day${dayCount === 1 ? '' : 's'}</b></div>

    ${cert.notes ? `
      <div class="section-title">Additional notes</div>
      <p style="font-size:12.5px; line-height:1.6; margin:4px 0 0;">${cert.notes}</p>
    ` : ''}

    <p style="font-size:12.5px; line-height:1.6; margin:28px 0 0;">
      This is to certify that the above-named patient was examined at ${clinicName} on
      ${formatDate(cert.visit_date)} and is advised to rest as stated above.
    </p>

    <div style="margin-top:48px; display:flex; justify-content:space-between; align-items:flex-end;">
      <div style="font-size:11px; color:#64748b;">Issued ${formatDateTime(cert.created_at)}</div>
      <div style="text-align:center;">
        <div style="border-top:1px solid #1a1a1a; width:220px; margin-top:40px; padding-top:4px; font-size:11px; color:#64748b;">
          Dr. ${cert.dentist_first_name} ${cert.dentist_last_name}
        </div>
      </div>
    </div>
  `;

  return wrapper({
    clinicName, logoUrl, docLabel: 'Medical Certificate', docId: String(cert.id).slice(0, 8).toUpperCase(), bodyHtml,
    footerNote: `This certificate is issued for the sole purpose of confirming attendance and fitness advice. Generated by ${clinicName}.`,
  });
};

module.exports = { medicalCertificateHtml };