const baseStyles = `
  * { box-sizing: border-box; }
  body { font-family: 'Helvetica', Arial, sans-serif; color: #1a1a1a; padding: 0; margin: 0; font-size: 13px; }
  .header { display: flex; align-items: center; justify-content: space-between; border-bottom: 3px solid #0A1730; padding-bottom: 16px; margin-bottom: 24px; }
  .header-left { display: flex; align-items: center; }
  .header-left img { height: 56px; margin-right: 14px; }
  .clinic-name { font-size: 19px; font-weight: 800; color: #0A1730; }
  .doc-title { text-align: right; }
  .doc-title .kind { font-size: 11px; letter-spacing: 0.06em; text-transform: uppercase; color: #64748b; font-weight: 600; }
  .doc-title .id { font-size: 15px; font-weight: 700; color: #0A1730; font-family: 'IBM Plex Mono', monospace; }
  table { width: 100%; border-collapse: collapse; margin-top: 10px; }
  th { text-align: left; padding: 8px; font-size: 11px; text-transform: uppercase; letter-spacing: 0.04em; color: #64748b; border-bottom: 2px solid #e2e8f0; }
  td { text-align: left; padding: 8px; border-bottom: 1px solid #e2e8f0; font-size: 12.5px; }
  .section-title { font-size: 13px; font-weight: 700; color: #0A1730; margin: 22px 0 4px; }
  .meta-row { display: flex; justify-content: space-between; font-size: 12.5px; margin: 3px 0; }
  .meta-row .label { color: #64748b; }
  .footer { margin-top: 40px; font-size: 10.5px; color: #64748b; border-top: 1px solid #e2e8f0; padding-top: 10px; }
  .badge { display: inline-block; padding: 2px 9px; border-radius: 999px; font-size: 11px; font-weight: 600; }
  .badge-paid, .badge-approved { background: #dcfce7; color: #166534; }
  .badge-unpaid, .badge-pending { background: #fef3c7; color: #92400e; }
  .badge-void, .badge-rejected { background: #fee2e2; color: #991b1b; }
`;

// docLabel: e.g. "INVOICE", "STATEMENT", "PRESCRIPTION", "TOOTH CHART HISTORY"
// docId: e.g. bill id, patient id — shown top-right for reference/filing
const wrapper = ({ clinicName, logoUrl, docLabel, docId, bodyHtml, footerNote }) => `
  <!DOCTYPE html>
  <html>
  <head><meta charset="utf-8"><style>${baseStyles}</style></head>
  <body>
    <div class="header">
      <div class="header-left">
        ${logoUrl ? `<img src="${logoUrl}" />` : ''}
        <div class="clinic-name">${clinicName}</div>
      </div>
      <div class="doc-title">
        <div class="kind">${docLabel}</div>
        ${docId ? `<div class="id">#${docId}</div>` : ''}
      </div>
    </div>
    ${bodyHtml}
    <div class="footer">${footerNote || `Generated by ${clinicName}. This is a computer-generated document.`}</div>
  </body>
  </html>
`;

const formatMoney = (n) => 'KSh ' + Number(n || 0).toLocaleString('en-KE');

const formatDate = (iso) =>
  new Date(iso).toLocaleDateString('en-KE', {
    timeZone: 'Africa/Nairobi', day: 'numeric', month: 'long', year: 'numeric',
  });

const formatDateTime = (iso) =>
  new Date(iso).toLocaleString('en-KE', {
    timeZone: 'Africa/Nairobi', day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit',
  });

module.exports = { wrapper, formatMoney, formatDate, formatDateTime };