const { wrapper, formatDate } = require('./pdfLayout');

// prescriptions: array of that day's Prescription rows (already filtered to
// one calendar date by the model query — see
// prescriptionModel.findPrescriptionsByPatientOnDate), each pre-enriched
// with a `dentist_name` field by the controller. Usually one dentist per
// day, but the table shows it per-row so a rare multi-dentist day still
// prints correctly rather than silently attributing everything to one name.
const prescriptionHtml = ({ patient, prescriptions, date }, clinicName, logoUrl) => {
  const rows = prescriptions.length
    ? prescriptions.map((rx) => `
        <tr>
          <td>${rx.drug_name}</td>
          <td>${rx.dosage || '—'}</td>
          <td>${rx.frequency || '—'}</td>
          <td>${rx.duration || '—'}</td>
          <td>Dr. ${rx.dentist_name}</td>
        </tr>
      `).join('')
    : `<tr><td colspan="5" style="color:#64748b;">No prescriptions recorded for this date.</td></tr>`;

  const notesHtml = prescriptions.some((rx) => rx.notes)
    ? `
      <div class="section-title">Notes</div>
      ${prescriptions.filter((rx) => rx.notes).map((rx) => `
        <div class="meta-row"><span class="label">${rx.drug_name}</span><span>${rx.notes}</span></div>
      `).join('')}
    `
    : '';

  const bodyHtml = `
    <div class="meta-row"><span class="label">Patient</span><b>${patient.first_name} ${patient.last_name}</b></div>
    <div class="meta-row"><span class="label">Date</span><b>${formatDate(date)}</b></div>

    <div style="font-size:26px; font-weight:800; color:#2F6FED; margin:20px 0 6px;">&#8477;</div>
    <table>
      <thead><tr><th>Medication</th><th>Dosage</th><th>Frequency</th><th>Duration</th><th>Dentist</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>
    ${notesHtml}

    <div style="margin-top:48px; display:flex; justify-content:flex-end;">
      <div style="text-align:center;">
        <div style="border-top:1px solid #1a1a1a; width:220px; margin-top:40px; padding-top:4px; font-size:11px; color:#64748b;">
          Dentist's signature
        </div>
      </div>
    </div>
  `;

  return wrapper({
    clinicName, logoUrl, docLabel: 'Prescription', docId: null, bodyHtml,
    footerNote: `Not valid without dentist signature. Generated by ${clinicName}.`,
  });
};

module.exports = { prescriptionHtml };